[tool.poetry]
name = "pygwalker"
version = "0.0.1"
description = "pygwalker: Combining Jupyter Notebook with a Tableau-like UI"
authors = ["Asm.Def <woojson@zju.edu.cn>"]
license = { file="LICENSE" }
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[tool.poetry.dependencies]
python = "^3.8"
jinja2 = "^3.1.2"
pandas = "^1.5.3"
ipython = "^8.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
